 
name: Auto Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # تحديث كل ساعة

jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update"
          git push
